# Generated by Django 4.2.7 on 2024-03-05 13:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="gymuser",
            name="membership_plan",
        ),
        migrations.RemoveField(
            model_name="gymuser",
            name="membership_status",
        ),
        migrations.AddField(
            model_name="gymuser",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
