# Generated by Django 4.2.7 on 2024-02-26 07:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="gymuser",
            name="age",
        ),
        migrations.RemoveField(
            model_name="gymuser",
            name="weight",
        ),
        migrations.AddField(
            model_name="gymuser",
            name="access_information",
            field=models.CharField(default="RFID", max_length=100),
        ),
        migrations.AddField(
            model_name="gymuser",
            name="address",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="gymuser",
            name="assigned_locker_number",
            field=models.CharField(blank=True, default="", max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="gymuser",
            name="assigned_personal_trainer",
            field=models.CharField(blank=True, default="", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="gymuser",
            name="contact_number",
            field=models.CharField(default="", max_length=15),
        ),
        migrations.AddField(
            model_name="gymuser",
            name="date_of_birth",
            field=models.DateField(default="1900-01-01"),
        ),
        migrations.AddField(
            model_name="gymuser",
            name="documents",
            field=models.FileField(blank=True, null=True, upload_to="documents/"),
        ),
        migrations.AddField(
            model_name="gymuser",
            name="email",
            field=models.EmailField(default="", max_length=254),
        ),
        migrations.AddField(
            model_name="gymuser",
            name="emergency_contact_name",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AddField(
            model_name="gymuser",
            name="emergency_contact_phone_number",
            field=models.CharField(default="", max_length=15),
        ),
        migrations.AddField(
            model_name="gymuser",
            name="emergency_contact_relationship",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AddField(
            model_name="gymuser",
            name="exercise_restrictions",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="gymuser",
            name="feedback",
            field=models.TextField(blank=True, default="", null=True),
        ),
        migrations.AddField(
            model_name="gymuser",
            name="first_name",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AddField(
            model_name="gymuser",
            name="fitness_goals",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="gymuser",
            name="gender",
            field=models.CharField(default="", max_length=10),
        ),
        migrations.AddField(
            model_name="gymuser",
            name="health_conditions",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="gymuser",
            name="joining_date",
            field=models.DateField(default="1900-01-01"),
        ),
        migrations.AddField(
            model_name="gymuser",
            name="last_name",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AddField(
            model_name="gymuser",
            name="membership_expiry_date",
            field=models.DateField(default="1900-01-01"),
        ),
        migrations.AddField(
            model_name="gymuser",
            name="membership_id_number",
            field=models.CharField(default="", max_length=50),
        ),
        migrations.AddField(
            model_name="gymuser",
            name="membership_plan",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AddField(
            model_name="gymuser",
            name="membership_status",
            field=models.CharField(
                choices=[
                    ("Active", "Active"),
                    ("Inactive", "Inactive"),
                    ("Suspended", "Suspended"),
                ],
                default="",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="gymuser",
            name="membership_type",
            field=models.CharField(
                choices=[("Monthly", "Monthly"), ("Annual", "Annual")],
                default="",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="gymuser",
            name="trainer_contact_information",
            field=models.CharField(blank=True, default="", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="gymuser",
            name="workout_schedule",
            field=models.TextField(default=""),
        ),
    ]
