# Generated by Django 4.2.7 on 2024-02-28 10:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_remove_gymuser_age_remove_gymuser_weight_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="GymEquipment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("cardio", "Cardio"),
                            ("strength", "Strength"),
                            ("free_weights", "Free Weights"),
                            ("machines", "Machines"),
                            ("other", "Other"),
                        ],
                        max_length=50,
                    ),
                ),
                ("manufacturer", models.CharField(max_length=100)),
                ("model_number", models.CharField(max_length=50)),
                ("purchase_date", models.DateField()),
                (
                    "purchase_price",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("warranty_information", models.TextField(blank=True, null=True)),
                ("warranty_expiration_date", models.DateField(blank=True, null=True)),
                (
                    "condition",
                    models.CharField(
                        choices=[
                            ("new", "New"),
                            ("used", "Used"),
                            ("refurbished", "Refurbished"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "maintenance_charge",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("availability", models.BooleanField(default=True)),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="equipment_images/"
                    ),
                ),
                ("additional_notes", models.TextField(blank=True, null=True)),
            ],
        ),
    ]
