# Generated by Django 4.2.7 on 2024-03-06 04:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_remove_gymuser_membership_plan_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="attendance",
            name="branch",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="api.branch",
            ),
        ),
        migrations.AddField(
            model_name="gymequipment",
            name="branch",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="api.branch",
            ),
        ),
        migrations.AddField(
            model_name="gymequipment",
            name="gym",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="api.gym",
            ),
        ),
        migrations.AddField(
            model_name="gymowner",
            name="branch_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="gymowner",
            name="gym_contact",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name="gymowner",
            name="gym_name",
            field=models.CharField(default="Default Gym Name", max_length=100),
        ),
        migrations.AddField(
            model_name="gymowner",
            name="place",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AddField(
            model_name="gymplan",
            name="branch",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="api.branch",
            ),
        ),
    ]
