# Generated by Django 4.2.7 on 2024-03-07 04:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0005_userweight"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gymequipment",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="gym_eqp_pictures/"
            ),
        ),
    ]
