# Generated by Django 4.2.7 on 2024-04-04 10:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0011_gymplanpayment"),
    ]

    operations = [
        migrations.AddField(
            model_name="gymplan",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="gym_plan_images"),
        ),
        migrations.AddField(
            model_name="gymplan",
            name="terms_and_conditions",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.CreateModel(
            name="PlanFeature",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("feature", models.CharField(max_length=255)),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="features",
                        to="api.gymplan",
                    ),
                ),
            ],
        ),
    ]
